### PR TITLE
adding tabulate

### PR DESCRIPTION
**Pull request by carlosedubarreto**
adding package tabulate, needed for the calibration script

### CODE REVIEW

**Comment by chingswy** [comment]
Hi @carlosedubarreto , does the new calibration pipeline work well?

**Comment by carlosedubarreto** [comment]
Hello @chingswy.
I made some tests yesterday and it at the end it did't seem to be working well.
But I dont know if I messed with something because I was using some previous footage I had already.

I'll have to make some new footage to test it all from scratch, to be sure of what I'm doing.

But the main problem I had was with the code that was already working on version 0.1. 
I had problems with extract_video. One problem I could fix, but there was more problems. So I ended up using the extract video fro the version 0.1

When running the` apps/demo/mv1p.py` I had problems too.

I saw that I'll need some more time to try and fix those problems that was happening, so I had to stop trying it now.

But I plan to get back on it as soon as I advance on the other project I'm working (addon for blender to import easymocap, frankmocap, vibe and mediapipe data)

**Comment by chingswy** [comment]
Can you report the problems you met?

**Comment by carlosedubarreto** [comment]
Some examples of why I think it didnt work well... when running the code to check_calib, it gives me these results

image

image

image


and when running the cube
image

**Comment by carlosedubarreto** [comment]
> Can you report the problems you met?

running the sample data I had this problem
image

in pure text:
(easymocap2) D:\MOCAP\EasyMocap_v2>python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl

  Demo code for multiple views and one person:

    - Input : 0_input/sample => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
    - Output: 1_output/sample
    - Body  : smpl=>neutral, body25

triangulation:   0%|                                                                           | 0/218 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 108, in <module>
    mv1pmf_skel(dataset, check_repro=True, args=args)
  File "apps/demo/mv1p.py", line 35, in mv1pmf_skel
    images, annots = dataset[nf]
  File "d:\mocap\easymocap_v2\easymocap\dataset\mv1pmf.py", line 72, in __getitem__
    images, annots_all = super().__getitem__(index)
  File "d:\mocap\easymocap_v2\easymocap\dataset\base.py", line 470, in __getitem__
    annname = join(self.annot_root, cam, self.annotlist[cam][index])
IndexError: list index out of range

**Comment by chingswy** [comment]
It seems that the calibration step is wrong. What about the results of `detect_calib.py`? The calibration will fail if the chessboard was not detected right.

**Comment by chingswy** [comment]
What is the structure of your folder `0_input/sample`? It must contain:
```bash
<root>
├── annots
├── images
├── ...
```
It seems that you don't have `annots` folder.

**Comment by carlosedubarreto** [comment]
> It seems that the calibration step is wrong. What about the results of `detect_calib.py`? The calibration will fail if the chessboard was not detected right.

Yeah, I wasnt worrying with the calibration step, because I think I could have missed something, and I'll try it again with a better footage...

What got me worried was that I couldnt run the sample code, with the extract video, he checks the openpose files (the already comes woth the sample) and it gives error when creating the annotation.

Here is an example running the extract video from scratch with the sample code (that already has the openpose data)
image

**Comment by carlosedubarreto** [comment]
> What is the structure of your folder `0_input/sample`? It must contain:
> 
> ```shell
> <root>
> ├── annots
> ├── images
> ├── ...
> ```
> 
> It seems that you don't have `annots` folder.

He created the annots folder automaticaly, but now looks like it created only the first folder and then it gives an error

image


the folder created running extract_video
image

the error that showed
image

**Comment by chingswy** [comment]
You can remove the folder `0_input/sample/images` and do this step again.

**Comment by chingswy** [comment]
> You can remove the folder `0_input/sample/images` and do this step again.

It's because when extracting `10.mp4` to `0_input/sample/images/10` it is not finished.

**Comment by carlosedubarreto** [comment]
> > You can remove the folder `0_input/sample/images` and do this step again.
> 
> It's because when extracting `10.mp4` to `0_input/sample/images/10` it is not finished.

😅 my bad...
Yeah now it is working.

Seemes like the code was fionishing the extraction from the folder, but it was not...
Thats a good thing to notice...

Let the script runn till it finished or if stopped on halfway, to erase that folder and run again.

Thanks.. 
One less problem 😊

**Comment by carlosedubarreto** [comment]
I'll create issues for the problems I find.
It will be better and serve for other people that may also have the same problem.

Thanks a lot..

**Comment by carlosedubarreto** [comment]
@chingswy Sorry....
Looks like the problem I was having as due to me messing with the sample code.
I erased everything and strarted all from the beggining....

Now I have all the openpose poses, annotations and images.
I'm testing the 

python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl

It seems to be working fine now 😅
Sorry for saying that there was a problem with the code. The problem was with me.

**Comment by chingswy** [comment]
That's good. Feel free to tell me if there still exist some bugs.

**Pull request merged**
